name: publish-docs
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Dokka
        run: ./gradlew :dokkaHtml
      - name: Publish Dokka
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build/dokka/html --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}